/**
 * E2EE state persistence using per-credential directories.
 *
 * [INPUT]: Dict generated by E2eeClient.export_state() (HPKE scheme, contains
 *          version="hpke_v1"), credential_layout helpers
 * [OUTPUT]: saveE2eeState(), loadE2eeState(), deleteE2eeState()
 * [POS]: E2EE session state persistence module supporting cross-process HPKE
 *        E2EE communication in the indexed multi-credential layout
 *
 * [PROTOCOL]:
 * 1. Update this header when logic changes
 * 2. Check the folder's CLAUDE.md after updating
 */

import { readFileSync, writeFileSync, existsSync, unlinkSync } from 'fs';
import { resolveCredentialPaths, hasLegacyLayout, legacyLayoutHint, writeSecureJson } from './credential_layout.js';

/**
 * Resolve the E2EE state path for a credential.
 * @param {string} credentialName - Credential name
 * @returns {string|null} E2EE state path or null
 */
function _e2eeStatePath(credentialName) {
    const paths = resolveCredentialPaths(credentialName);
    if (paths === null) {
        return null;
    }
    return paths.e2eeStatePath;
}

/**
 * Save E2EE client state into the credential directory.
 * @param {Object} state - E2EE state object
 * @param {string} credentialName - Credential name (default: 'default')
 * @returns {string} Path to saved state file
 */
export function saveE2eeState(state, credentialName = 'default') {
    const path = _e2eeStatePath(credentialName);
    if (path === null) {
        throw new Error(
            `Credential '${credentialName}' not found; cannot save E2EE state`
        );
    }
    writeSecureJson(path, state);
    console.debug(`Saved E2EE state credential=${credentialName} path=${path}`);
    return path;
}

/**
 * Load E2EE client state from the credential directory.
 * @param {string} credentialName - Credential name (default: 'default')
 * @returns {Object|null} E2EE state object or null
 */
export function loadE2eeState(credentialName = 'default') {
    const path = _e2eeStatePath(credentialName);
    if (path === null) {
        if (hasLegacyLayout()) {
            console.error(legacyLayoutHint());
        }
        return null;
    }
    if (existsSync(path)) {
        console.debug(`Loaded E2EE state credential=${credentialName} path=${path}`);
        return JSON.parse(readFileSync(path, 'utf-8'));
    }
    return null;
}

/**
 * Delete a saved E2EE state file from the credential directory.
 * @param {string} credentialName - Credential name (default: 'default')
 * @returns {boolean} True if deleted, false if not found
 */
export function deleteE2eeState(credentialName = 'default') {
    const path = _e2eeStatePath(credentialName);
    if (path === null) {
        if (hasLegacyLayout()) {
            console.error(legacyLayoutHint());
        }
        return false;
    }
    if (existsSync(path)) {
        unlinkSync(path);
        console.info(`Deleted E2EE state credential=${credentialName} path=${path}`);
        return true;
    }
    return false;
}

export default {
    deleteE2eeState,
    loadE2eeState,
    saveE2eeState
};
