/**
 * E2EE state persistence using per-credential directories.
 *
 * Node.js implementation based on Python version:
 * python/scripts/e2ee_store.py
 *
 * [INPUT]: Dict generated by E2eeClient.export_state() (HPKE scheme, contains
 *          version="hpke_v1"), credential_layout helpers
 * [OUTPUT]: save_e2ee_state(), load_e2ee_state(), delete_e2ee_state()
 * [POS]: E2EE session state persistence module supporting cross-process HPKE
 *        E2EE communication in the indexed multi-credential layout
 */

const fs = require('fs');
const path = require('path');
const {
  hasLegacyLayout,
  legacyLayoutHint,
  resolveCredentialPaths
} = require('./credential-layout');

/**
 * Resolve the E2EE state path for a credential.
 * @param {string} credentialName - Credential name
 * @returns {string|null} E2EE state path or null
 */
function _e2ee_state_path(credentialName) {
  const paths = resolveCredentialPaths(credentialName);
  if (paths === null) {
    return null;
  }
  return paths.e2ee_state_path;
}

/**
 * Save E2EE client state into the credential directory.
 *
 * @param {Object} state - E2EE client state
 * @param {string} [credentialName="default"] - Credential name
 * @returns {string} Path to saved state file
 * @throws {Error} If credential not found
 */
function save_e2ee_state(state, credentialName = "default") {
  const statePath = _e2ee_state_path(credentialName);
  if (statePath === null) {
    throw new Error(
      `Credential '${credentialName}' not found; cannot save E2EE state`
    );
  }

  // Write secure JSON
  const dir = path.dirname(statePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }

  fs.writeFileSync(statePath, JSON.stringify(state, null, 2), { mode: 0o600 });
  return statePath;
}

/**
 * Load E2EE client state from the credential directory.
 *
 * @param {string} [credentialName="default"] - Credential name
 * @returns {Object|null} E2EE state or null
 */
function load_e2ee_state(credentialName = "default") {
  const statePath = _e2ee_state_path(credentialName);
  if (statePath === null) {
    if (hasLegacyLayout()) {
      console.error(legacyLayoutHint());
    }
    return null;
  }

  if (fs.existsSync(statePath)) {
    const content = fs.readFileSync(statePath, 'utf-8');
    return JSON.parse(content);
  }
  return null;
}

/**
 * Delete a saved E2EE state file from the credential directory.
 *
 * @param {string} [credentialName="default"] - Credential name
 * @returns {boolean} True if deleted
 */
function delete_e2ee_state(credentialName = "default") {
  const statePath = _e2ee_state_path(credentialName);
  if (statePath === null) {
    if (hasLegacyLayout()) {
      console.error(legacyLayoutHint());
    }
    return false;
  }

  if (fs.existsSync(statePath)) {
    fs.unlinkSync(statePath);
    return true;
  }
  return false;
}

module.exports = {
  save_e2ee_state,
  load_e2ee_state,
  delete_e2ee_state,
  // Also export with snake_case for Python compatibility
  save_e2ee_state: save_e2ee_state,
  load_e2ee_state: load_e2ee_state,
  delete_e2ee_state: delete_e2ee_state
};
