"""E2EE state persistence: save/load E2eeClient state to local files.

[INPUT]: Dict generated by E2eeClient.export_state() (HPKE scheme, contains version="hpke_v1"), SDKConfig (credentials_dir)
[OUTPUT]: save_e2ee_state(), load_e2ee_state(), delete_e2ee_state()
[POS]: E2EE session state persistence module supporting cross-process HPKE E2EE encrypted communication

[PROTOCOL]:
1. Update this header when logic changes
2. Check the folder's CLAUDE.md after updating
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path
from typing import Any

from utils.config import SDKConfig


def _get_credentials_dir() -> Path:
    """Get the credentials directory from SDKConfig."""
    return SDKConfig().credentials_dir


def _ensure_credentials_dir() -> Path:
    """Ensure credentials directory exists with proper permissions."""
    cred_dir = _get_credentials_dir()
    cred_dir.mkdir(parents=True, exist_ok=True)
    os.chmod(cred_dir, stat.S_IRWXU)
    return cred_dir


def _e2ee_state_path(credential_name: str) -> Path:
    """Get E2EE state file path."""
    return _ensure_credentials_dir() / f"e2ee_{credential_name}.json"


def save_e2ee_state(state: dict[str, Any], credential_name: str = "default") -> Path:
    """Save E2EE client state to a local file.

    Args:
        state: Dict generated by ``E2eeClient.export_state()``.
        credential_name: Credential name (default ``"default"``).

    Returns:
        State file path.
    """
    path = _e2ee_state_path(credential_name)
    path.write_text(json.dumps(state, indent=2, ensure_ascii=False))
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    return path


def load_e2ee_state(credential_name: str = "default") -> dict[str, Any] | None:
    """Load E2EE client state from a local file.

    Args:
        credential_name: Credential name (default ``"default"``).

    Returns:
        State dict, or None if not found.
    """
    path = _e2ee_state_path(credential_name)
    if path.exists():
        return json.loads(path.read_text())

    return None


def delete_e2ee_state(credential_name: str = "default") -> bool:
    """Delete a saved E2EE state file.

    Args:
        credential_name: Credential name (default ``"default"``).

    Returns:
        Whether deletion was successful.
    """
    path = _e2ee_state_path(credential_name)
    if path.exists():
        path.unlink()
        return True
    return False
